using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Yoyoyopo5.ValueWrapper.Tests.Shared;

namespace Yoyoyopo5.ValueWrapper.Generator.Tests;

public class Test_ValueWrapperGenerator_Generation
{
    private const string FAKE_CONVERTER = """
        using System;
        using System.Text.Json;
        using System.Text.Json.Serialization;
        using System.ComponentModel;

        namespace TestNamespace;
        public class FakeJsonConverter<T> : JsonConverter<T>
        {
            public override T? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
            {
                throw new NotImplementedException();
            }
            public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
            {
                throw new NotImplementedException();
            }
        }

        public class FakeTypeConverter : TypeConverter { }

        """;

    private const string EXPECTED_FILE_PATH_SUFFIX = "_Wrapper.g.cs";
    private readonly static SourceGeneratorTestCase[] _testCases =
    [
        new SourceGeneratorTestCase()
        {
            Name = "AddsAllMembersToEmptyType",
            Input = """
            using Yoyoyopo5.ValueWrapper;
            namespace TestNamespace;
            [Wrapper<string>]
            public readonly partial record struct AddsAllMembersToEmptyType;
            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;

            [global::System.Text.Json.Serialization.JsonConverter(typeof(global::Yoyoyopo5.ValueWrapper.WrapperJsonConverter<AddsAllMembersToEmptyType, global::System.String>))]
            [global::System.ComponentModel.TypeConverter(typeof(global::Yoyoyopo5.ValueWrapper.WrapperTypeConverter<AddsAllMembersToEmptyType, global::System.String>))]
            public readonly partial record struct AddsAllMembersToEmptyType
                : global::Yoyoyopo5.ValueWrapper.IWrapValue<global::System.String, AddsAllMembersToEmptyType>
            {
                public required global::System.String Value { get; init; }
                public static implicit operator global::System.String(AddsAllMembersToEmptyType wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value.ToString();
                static AddsAllMembersToEmptyType global::Yoyoyopo5.ValueWrapper.IWrapValue<global::System.String, AddsAllMembersToEmptyType>.Create(global::System.String value) => new() { Value = value };
            }

            """,
            ExpectedOutputFilePath = $"TestNamespace_AddsAllMembersToEmptyType{EXPECTED_FILE_PATH_SUFFIX}"
        },
        new SourceGeneratorTestCase()
        {
            Name = "AddsCreateMethodToFullType",
            Input = """
            using Yoyoyopo5.ValueWrapper;
            using System.Text.Json.Serialization;
            using System.ComponentModel;
            namespace TestNamespace;
            [Wrapper<string>]
            [JsonConverter(typeof(FakeJsonConverter<string>))]
            [TypeConverter(typeof(FakeTypeConverter))]
            public readonly partial record struct AddsCreateMethodToFullType
            {
                public required string Value { get; init; }
                public override string ToString() => Value;
                public static implicit operator string(AddsCreateMethodToFullType wrapper) => wrapper.Value;
            }
            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable
            
            namespace TestNamespace;
            
            public readonly partial record struct AddsCreateMethodToFullType
                : global::Yoyoyopo5.ValueWrapper.IWrapValue<global::System.String, AddsCreateMethodToFullType>
            {
                static AddsCreateMethodToFullType global::Yoyoyopo5.ValueWrapper.IWrapValue<global::System.String, AddsCreateMethodToFullType>.Create(global::System.String value) => new() { Value = value };
            }

            """,
            ExpectedOutputFilePath = $"TestNamespace_AddsCreateMethodToFullType{EXPECTED_FILE_PATH_SUFFIX}"
        },
        new SourceGeneratorTestCase()
        {
            Name = "SkipsGeneratingNonPartialRecord",
            Input = """
            namespace TestNamespace;
            using Yoyoyopo5.ValueWrapper;
            [Wrapper<string>]
            public record SkipsGeneratingNonPartialRecord;
            """,
            ExpectedOutput = null,
            ExpectedOutputFilePath = null
        },
        new SourceGeneratorTestCase()
        {
            Name = "GeneratesNestedWrapperType",
            Input = """
            namespace TestNamespace;
            using Yoyoyopo5.ValueWrapper;
            public partial class ContainerOne
            {
                public partial class ContainerTwo
                {
                    [Wrapper<int>]
                    private partial class GeneratesNestedWrapperType { }
                }
            }
            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable
            
            namespace TestNamespace;
            
            public partial class ContainerOne
            {
                public partial class ContainerTwo
                {
                    [global::System.Text.Json.Serialization.JsonConverter(typeof(global::Yoyoyopo5.ValueWrapper.WrapperJsonConverter<GeneratesNestedWrapperType, global::System.Int32>))]
                    [global::System.ComponentModel.TypeConverter(typeof(global::Yoyoyopo5.ValueWrapper.WrapperTypeConverter<GeneratesNestedWrapperType, global::System.Int32>))]
                    private partial class GeneratesNestedWrapperType
                        : global::Yoyoyopo5.ValueWrapper.IWrapValue<global::System.Int32, GeneratesNestedWrapperType>
                    {
                        public required global::System.Int32 Value { get; init; }
                        public static implicit operator global::System.Int32(GeneratesNestedWrapperType wrapper) => wrapper.Value;
                        public override global::System.String ToString() => Value.ToString();
                        static GeneratesNestedWrapperType global::Yoyoyopo5.ValueWrapper.IWrapValue<global::System.Int32, GeneratesNestedWrapperType>.Create(global::System.Int32 value) => new() { Value = value };
                    }
                }
            }
            
            """,
            ExpectedOutputFilePath = $"TestNamespace_ContainerOne_ContainerTwo_GeneratesNestedWrapperType{EXPECTED_FILE_PATH_SUFFIX}"
        },
        new SourceGeneratorTestCase()
        {
            Name = "SkipsValuePropertyOnRecordWithPrimaryConstructor",
            Input = """
            namespace TestNamespace;
            using Yoyoyopo5.ValueWrapper;
            [Wrapper<double>]
            public partial record SkipsValuePropertyOnRecordWithPrimaryConstructor(double Value);
            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable
            
            namespace TestNamespace;
            
            [global::System.Text.Json.Serialization.JsonConverter(typeof(global::Yoyoyopo5.ValueWrapper.WrapperJsonConverter<SkipsValuePropertyOnRecordWithPrimaryConstructor, global::System.Double>))]
            [global::System.ComponentModel.TypeConverter(typeof(global::Yoyoyopo5.ValueWrapper.WrapperTypeConverter<SkipsValuePropertyOnRecordWithPrimaryConstructor, global::System.Double>))]
            public partial record class SkipsValuePropertyOnRecordWithPrimaryConstructor
                : global::Yoyoyopo5.ValueWrapper.IWrapValue<global::System.Double, SkipsValuePropertyOnRecordWithPrimaryConstructor>
            {
                public static implicit operator global::System.Double(SkipsValuePropertyOnRecordWithPrimaryConstructor wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value.ToString();
                static SkipsValuePropertyOnRecordWithPrimaryConstructor global::Yoyoyopo5.ValueWrapper.IWrapValue<global::System.Double, SkipsValuePropertyOnRecordWithPrimaryConstructor>.Create(global::System.Double value) => new(value);
            }
            
            """,
            ExpectedOutputFilePath = $"TestNamespace_SkipsValuePropertyOnRecordWithPrimaryConstructor{EXPECTED_FILE_PATH_SUFFIX}"
        },
        new SourceGeneratorTestCase()
        {
            Name = "SkipsGeneratingRecordWithWronglyTypedPrimaryConstructor",
            Input = """
            namespace TestNamespace;
            using Yoyoyopo5.ValueWrapper;
            [Wrapper<string>]
            public partial record SkipsGeneratingRecordWithWronglyTypedPrimaryConstructor(int Value);
            """,
            ExpectedOutput = null,
            ExpectedOutputFilePath = null
        },
        new SourceGeneratorTestCase()
        {
            Name = "SkipsGeneratingClassWithWronglyTypedValueProperty",
            Input = """
            namespace TestNamespace;
            using Yoyoyopo5.ValueWrapper;
            [Wrapper<string>]
            public partial class SkipsGeneratingClassWithWronglyTypedValueProperty
            {
                public int Value { get; init; }
            }
            """,
            ExpectedOutput = null,
            ExpectedOutputFilePath = null
        },
        new SourceGeneratorTestCase()
        {
            Name = "SkipsAddingConvertersWithNonValueRequiredProps",
            Input = """
            namespace TestNamespace;
            using Yoyoyopo5.ValueWrapper;
            [Wrapper<string>]
            public partial record SkipsAddingConvertersWithNonValueRequiredProps
            {
                public required int Amount { get; init; }
            }
            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable
            
            namespace TestNamespace;
            
            public partial record class SkipsAddingConvertersWithNonValueRequiredProps
            {
                public required global::System.String Value { get; init; }
                public static implicit operator global::System.String(SkipsAddingConvertersWithNonValueRequiredProps wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value.ToString();
            }

            """,
            ExpectedOutputFilePath = $"TestNamespace_SkipsAddingConvertersWithNonValueRequiredProps{EXPECTED_FILE_PATH_SUFFIX}"
        },
        new SourceGeneratorTestCase()
        {
            Name = "SkipsAddingConvertersOnRecordWithNonValuePrimaryConstructorArgs",
            Input = """
            namespace TestNamespace;
            using Yoyoyopo5.ValueWrapper;
            [Wrapper<string>]
            public partial record SkipsAddingConvertersOnRecordWithNonValuePrimaryConstructorArgs(int Amount);
            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable
            
            namespace TestNamespace;
            
            public partial record class SkipsAddingConvertersOnRecordWithNonValuePrimaryConstructorArgs
            {
                public required global::System.String Value { get; init; }
                public static implicit operator global::System.String(SkipsAddingConvertersOnRecordWithNonValuePrimaryConstructorArgs wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value.ToString();
            }

            """,
            ExpectedOutputFilePath = $"TestNamespace_SkipsAddingConvertersOnRecordWithNonValuePrimaryConstructorArgs{EXPECTED_FILE_PATH_SUFFIX}"
        },
        new SourceGeneratorTestCase()
        {
            Name = "AddsConvertersWithNonValueRequiredPropsAndSuitableStaticCreateMethod",
            Input = """
            namespace TestNamespace;
            using Yoyoyopo5.ValueWrapper;
            [Wrapper<string>]
            public partial record AddsConvertersWithNonValueRequiredPropsAndSuitableStaticCreateMethod(int OtherAmount)
            {
                public string Value => (Amount + OtherAmount).ToString();
                public required int Amount { get; init; }
                public static AddsConvertersWithNonValueRequiredPropsAndSuitableStaticCreateMethod Create(string amount)
                    => new(0) { Amount = int.Parse(amount) };
            }

            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable
            
            namespace TestNamespace;
            
            [global::System.Text.Json.Serialization.JsonConverter(typeof(global::Yoyoyopo5.ValueWrapper.WrapperJsonConverter<AddsConvertersWithNonValueRequiredPropsAndSuitableStaticCreateMethod, global::System.String>))]
            [global::System.ComponentModel.TypeConverter(typeof(global::Yoyoyopo5.ValueWrapper.WrapperTypeConverter<AddsConvertersWithNonValueRequiredPropsAndSuitableStaticCreateMethod, global::System.String>))]
            public partial record class AddsConvertersWithNonValueRequiredPropsAndSuitableStaticCreateMethod
                : global::Yoyoyopo5.ValueWrapper.IWrapValue<global::System.String, AddsConvertersWithNonValueRequiredPropsAndSuitableStaticCreateMethod>
            {
                public static implicit operator global::System.String(AddsConvertersWithNonValueRequiredPropsAndSuitableStaticCreateMethod wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value.ToString();
                static AddsConvertersWithNonValueRequiredPropsAndSuitableStaticCreateMethod global::Yoyoyopo5.ValueWrapper.IWrapValue<global::System.String, AddsConvertersWithNonValueRequiredPropsAndSuitableStaticCreateMethod>.Create(global::System.String value) => Create(value);
            }

            """,
            ExpectedOutputFilePath = $"TestNamespace_AddsConvertersWithNonValueRequiredPropsAndSuitableStaticCreateMethod{EXPECTED_FILE_PATH_SUFFIX}"
        },
        new SourceGeneratorTestCase()
        {
            Name = "AddMembersToWrappedNullableValueType",
            Input = """
            namespace TestNamespace;
            using Yoyoyopo5.ValueWrapper;
            using System.Text.Json.Serialization;
            [Wrapper<int?>]
            public readonly partial record struct AddMembersToWrappedNullableValueType;
            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable
            
            namespace TestNamespace;
            
            [global::System.Text.Json.Serialization.JsonConverter(typeof(global::Yoyoyopo5.ValueWrapper.WrapperJsonConverter<AddMembersToWrappedNullableValueType, global::System.Int32?>))]
            [global::System.ComponentModel.TypeConverter(typeof(global::Yoyoyopo5.ValueWrapper.WrapperTypeConverter<AddMembersToWrappedNullableValueType, global::System.Int32?>))]
            public readonly partial record struct AddMembersToWrappedNullableValueType
                : global::Yoyoyopo5.ValueWrapper.IWrapValue<global::System.Int32?, AddMembersToWrappedNullableValueType>
            {
                public global::System.Int32? Value { get; init; }
                public static implicit operator global::System.Int32?(AddMembersToWrappedNullableValueType wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value?.ToString() ?? global::System.String.Empty;
                static AddMembersToWrappedNullableValueType global::Yoyoyopo5.ValueWrapper.IWrapValue<global::System.Int32?, AddMembersToWrappedNullableValueType>.Create(global::System.Int32? value) => new() { Value = value };
            }

            """,
            ExpectedOutputFilePath = $"TestNamespace_AddMembersToWrappedNullableValueType{EXPECTED_FILE_PATH_SUFFIX}"
        },
        new SourceGeneratorTestCase()
        {
            Name = "SkipsGeneratingStaticWrapperType",
            Input = """
            namespace TestNamespace;
            using Yoyoyopo5.ValueWrapper;

            [Wrapper<string>]
            public static partial class SkipsGeneratingStaticWrapperType;
            """,
            ExpectedOutput = null,
            ExpectedOutputFilePath = null
        },
        new SourceGeneratorTestCase()
        {
            Name = "AddsConvertersToFullWrapper",
            Input = """
            namespace TestNamespace;
            using Yoyoyopo5.ValueWrapper;

            [Wrapper<int>]
            public partial class AddsConvertersToFullWrapper
            {
                public required int Value { get; init; }
                public override string ToString() => Value.ToString();
                public static implicit operator int(AddsConvertersToFullWrapper wrapper) => wrapper.Value;
                public static AddsConvertersToFullWrapper Create(int value) => new() { Value = value };
            }
            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable
            
            namespace TestNamespace;
            
            [global::System.Text.Json.Serialization.JsonConverter(typeof(global::Yoyoyopo5.ValueWrapper.WrapperJsonConverter<AddsConvertersToFullWrapper, global::System.Int32>))]
            [global::System.ComponentModel.TypeConverter(typeof(global::Yoyoyopo5.ValueWrapper.WrapperTypeConverter<AddsConvertersToFullWrapper, global::System.Int32>))]
            public partial class AddsConvertersToFullWrapper
                : global::Yoyoyopo5.ValueWrapper.IWrapValue<global::System.Int32, AddsConvertersToFullWrapper>
            {
                static AddsConvertersToFullWrapper global::Yoyoyopo5.ValueWrapper.IWrapValue<global::System.Int32, AddsConvertersToFullWrapper>.Create(global::System.Int32 value) => Create(value);
            }

            """,
            ExpectedOutputFilePath = $"TestNamespace_AddsConvertersToFullWrapper{EXPECTED_FILE_PATH_SUFFIX}"
        },
        new SourceGeneratorTestCase()
        {
            Name = "AddsMembersForWrappedArray",
            Input = """
            namespace TestNamespace;
            using Yoyoyopo5.ValueWrapper;

            [Wrapper<string[]>]
            public partial class AddsMembersForWrappedArray;
            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable
            
            namespace TestNamespace;
            
            [global::System.Text.Json.Serialization.JsonConverter(typeof(global::Yoyoyopo5.ValueWrapper.WrapperJsonConverter<AddsMembersForWrappedArray, global::System.String[]>))]
            [global::System.ComponentModel.TypeConverter(typeof(global::Yoyoyopo5.ValueWrapper.WrapperTypeConverter<AddsMembersForWrappedArray, global::System.String[]>))]
            public partial class AddsMembersForWrappedArray
                : global::Yoyoyopo5.ValueWrapper.IWrapValue<global::System.String[], AddsMembersForWrappedArray>
            {
                public required global::System.String[] Value { get; init; }
                public static implicit operator global::System.String[](AddsMembersForWrappedArray wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value.ToString();
                static AddsMembersForWrappedArray global::Yoyoyopo5.ValueWrapper.IWrapValue<global::System.String[], AddsMembersForWrappedArray>.Create(global::System.String[] value) => new() { Value = value };
            }
            
            """,
            ExpectedOutputFilePath = $"TestNamespace_AddsMembersForWrappedArray{EXPECTED_FILE_PATH_SUFFIX}"
        }
    ];
    public static TheoryData<TestCaseWrapper<SourceGeneratorTestCase>> TestCases
        => [.. _testCases.Select(t => new TestCaseWrapper<SourceGeneratorTestCase>(t))];

    private static CSharpSourceGeneratorTest<ValueWrapperGenerator, DefaultVerifier> CreateGeneratorTest()
    {
        CSharpSourceGeneratorTest<ValueWrapperGenerator, DefaultVerifier> test = new()
        {
            ReferenceAssemblies = ReferenceAssemblies.Net.Net100
        };
        test.TestState.AdditionalReferences.Add(typeof(WrapperAttribute<>).Assembly);
        test.TestState.Sources.Add(FAKE_CONVERTER);
        return test;
    }

    [Theory]
    [MemberData(nameof(TestCases))]
    public async Task Generator(TestCaseWrapper<SourceGeneratorTestCase> @case)
        => await @case.TestCase.Register(CreateGeneratorTest()).RunAsync(TestContext.Current.CancellationToken);
}